// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistrodeUsuarios.DAL;

namespace RegistrodeUsuarios.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211110030855_Migracion_Inicial")]
    partial class Migracion_Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("RegistrodeUsuarios.Entidades.Usuarios", b =>
                {
                    b.Property<int>("Usuarioid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contrasena")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreDeUsuario")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .HasColumnType("TEXT");

                    b.HasKey("Usuarioid");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Usuarioid = 1,
                            Apellidos = "Diaz",
                            Contrasena = "cffa965d9faa1d453f2d336294b029a7f84f485f75ce2a2c723065453b12b03b",
                            NombreDeUsuario = "profesor",
                            Nombres = "Reny"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
